
services:
  zendesk-mcp:
    build: .
    # No container_name to allow scaling
    # No external ports - nginx will handle external access
    environment:
      - ZENDESK_BASE_URL=${ZENDESK_BASE_URL}
      - ZENDESK_EMAIL=${ZENDESK_EMAIL}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8021}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:${SERVER_PORT:-8021}/status')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zendesk-mcp-network
    # Use entrypoint.sh for mcp-proxy
    command: ["./entrypoint.sh"]

  # Nginx load balancer (always enabled)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zendesk-mcp
    restart: unless-stopped
    networks:
      - zendesk-mcp-network

networks:
  zendesk-mcp-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
